### ISSUE TITLE
Snappy does not have compression methods GPF and jpy

### ISSUE THREAD

**Issue by tillea** [snap-contrib/snapista#21]
Hi,
I've tried to build snapista forDebian but I was running into a build time test issue which boils down to:

    $ python3
    Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from snappy import GPF
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'GPF' from 'snappy' (/usr/lib/python3/dist-packages/snappy/__init__.py)
    >>> from snappy import jpy
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'jpy' from 'snappy' (/usr/lib/python3/dist-packages/snappy/__init__.py)

I've [reported this on snappy](https://github.com/andrix/python-snappy/issues/126) but they said: `GPF and jpy don't sound like they have anything to do with this package, I don't think there have ever been things named like that.`

Do you have any hint what to do to get GPF and jpy?

Kind regards, Andreas.

**Comment by Mako18** [comment]
Hi,
I've a similar issue. I installed snapista with mamba and following the specified instruction:

`conda install -c terradue snapista
`

However, when I try to import it, I get the following error:

![Image](https://github.com/user-attachments/assets/123c7e1d-b9e7-4f94-b6bd-426653f5a6a4)

Any clue on how can I solve this? Thanks.
